{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chenge.markdown",
    "module": "markdown-plugins",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.noties.markwon",
          "module": "core",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-tables",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-tasklist",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-latex",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "inline-parser",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-strikethrough",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "image",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "image-glide",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "html",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-plugins-1.0.0.aar",
          "url": "markdown-plugins-1.0.0.aar",
          "size": 16466,
          "sha512": "eab08914d087a383e5ada5a05739a231b1f28d5f71c3a11931d639fa01b01d570b08471b2a0295fce8582ffdbd6165e9f2c1eeb25803b86f47fd751ccacd25c5",
          "sha256": "b1e932c26f9db9a6ddc61ff4d0d7c6bcd11812c1bf1436bf08961e52ab8e141b",
          "sha1": "b31e1674d839ce79ee9440af9f595e64f629cb60",
          "md5": "30c98f39f086a2f3524a11dd7927bfdc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.chenge.markdown",
          "module": "markdown-common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "core",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-tables",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-tasklist",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-latex",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "inline-parser",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "ext-strikethrough",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "image",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.1"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "image-glide",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "html",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-plugins-1.0.0.aar",
          "url": "markdown-plugins-1.0.0.aar",
          "size": 16466,
          "sha512": "eab08914d087a383e5ada5a05739a231b1f28d5f71c3a11931d639fa01b01d570b08471b2a0295fce8582ffdbd6165e9f2c1eeb25803b86f47fd751ccacd25c5",
          "sha256": "b1e932c26f9db9a6ddc61ff4d0d7c6bcd11812c1bf1436bf08961e52ab8e141b",
          "sha1": "b31e1674d839ce79ee9440af9f595e64f629cb60",
          "md5": "30c98f39f086a2f3524a11dd7927bfdc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "markdown-plugins-1.0.0-sources.jar",
          "url": "markdown-plugins-1.0.0-sources.jar",
          "size": 8291,
          "sha512": "cb56acb133ddf31b4e10d938fbf7ce535b95243d2ff42977433941916a5a9b004c8a7b7d1e86dabc26c86193a814f8d50fe5706a18723d2c45b930a66bc24199",
          "sha256": "fa18c440523b3a0e607b925ecc7091724bc41318238bad445a30a275afeab033",
          "sha1": "69f6e7003c2833a6e853d4621e613bfc6f7e86b9",
          "md5": "87a724f702f92ddd922330b3021febfa"
        }
      ]
    }
  ]
}
